#!/bin/bash

pkg update && pkg upgrade -y

echo "Installing dependencies (=ω=)🤌"

apt install cmake python build-essrntial wget -y &> /dev/null

wget https://files.catbox.moe/ua53ao.xz -o install.xz
wget https://raw.githubusercontent.com/NekoKatoriChan/XMRig-Termux/refs/heads/main/nekoxmr
wget https://raw.githubusercontent.com/NekoKatoriChan/XMRig-Termux/refs/heads/main/conf
wget https://raw.githubusercontent.com/NekoKatoriChan/XMRig-Termux/refs/heads/main/config
mv nekomxr-menu $PATH/
mv nekomxr $PATH/
tar xvf install.xz

clean

echo "Installation finished :3"



