#!/bin/bash

pkg update && pkg upgrade -y

echo "Installing dependencies (=ω=)🤌"

apt install cmake python wget -y &> /dev/null

wget https://raw.githubusercontent.com/NekoKatoriChan/XMRig-Termux/main/nekoxmr -O $PATH/nekoxmr
wget https://raw.githubusercontent.com/NekoKatoriChan/XMRig-Termux/main/conf
wget https://raw.githubusercontent.com/NekoKatoriChan/XMRig-Termux/main/config -O $PATH/nekoxmr-conf
wget https://raw.githubusercontent.com/NekoKatoriChan/XMRig-Termux/main/xmrig -O $PATH/config
chmod +x "$PREFIX/bin/nekoxmr" 


echo "Installation finished :3"
