#!/bin/bash

source conf

cd ~/xmrig/build || exit 1  

termux-wake-lock  


while true; do
    echo "Start mining...."
    
    ./xmrig -o "$POOL:$PORT" -u "$WALLET" -p x -a rx/0 -k --threads "$CPU" --cpu-priority 4 --randomx-mode "$MODE" --av=2 --donate-level 1 &

    MINER_PID=$!  

    sleep $MINE_TIME

    echo "Break time...."
    killall xmrig

    sleep $REST

    echo "Continue mining :3"
done
